# Generated by Django 4.0.4 on 2022-07-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_chat_sender_chat_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
